version: 2
updates:
  # Python (pip) updates
  - package-ecosystem: "pip"  # Update Python dependencies using pip
    directory: "/"  # Location of requirements.txt or pyproject.toml
    schedule:
      interval: "weekly"  # Check for updates every week