version: 2
updates:
  # Python (pip) updates
  - package-ecosystem: "uv"  # Update Python dependencies using uv
    directory: "/"  # Location of pyproject.toml
    schedule:
      interval: "weekly"  # Check for updates every week