version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres-db
    hostname: postgres-db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6000:6000"
    command: -p 6000

volumes:
  postgres_data: