version: '3.8'

services:
  yoasobi-morpheme-extractor:
    image: sakanbeer88/yoasobi-morpheme-extractor:latest
    container_name: yoasobi-morpheme-extractor
    hostname: yoasobi-morpheme-extractor
    volumes:
      - ./lyrics:/app/lyrics
      - ./visual_output:/app/visual_output
    depends_on:
      - yoasobi-morpheme-extractor-db
    env_file:
      - ./.env
    ports:
      - "8000:8000"

  yoasobi-morpheme-extractor-db:
    image: postgres:latest
    container_name: postgres-db
    hostname: postgres-db
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "6000:6000"
    command: -p 6000

volumes:
  postgres_data: