name: Trivy Docker Scan

on:
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build the Docker Image
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ vars.DOCKERHUB_USERNAME }}/jp-morphemes-extractor:latest

      - name: Run Trivy vulnerability scanner for Docker Image
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: '${{ vars.DOCKERHUB_USERNAME }}/jp-morphemes-extractor:latest'
          format: 'table'
